spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/pontta_ofc
spring.datasource.username=postgres
spring.datasource.password=Jhon303079

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true